DROP TABLE IF EXISTS VEHICLE;
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS [USER];
DROP TABLE IF EXISTS RIDE;

CREATE TABLE Vehicle
(
VehicleID INT NOT NULL,
LicencePlate CHAR NOT NULL,
Make VARCHAR NOT NULL,
Model VARCHAR NOT NULL,
Year INT NOT NULL,
PRIMARY KEY (VehicleID)
);

CREATE TABLE Payment
(
PaymentID INT NOT NULL,
PaymentMethod VARCHAR NOT NULL,
FareAmount NUMERIC NOT NULL,
Status VARCHAR NOT NULL,
Date DATE NOT NULL,
PRIMARY KEY (PaymentID)
);

CREATE TABLE Location
(
LocationID INT NOT NULL,
Address VARCHAR NOT NULL,
Latitude NUMERIC NOT NULL,
Longitude NUMERIC NOT NULL,
RideID INT NOT NULL,
PRIMARY KEY (LocationID)
);

CREATE TABLE [User]
(
UserID INT NOT NULL,
FName VARCHAR NOT NULL,
LName VARCHAR NOT NULL,
Current_Location NUMERIC NOT NULL,
Role VARCHAR,
PRIMARY KEY (UserID)
);

CREATE TABLE Ride
(
RideID INT NOT NULL,
StartTime INT NOT NULL,
EndTime INT NOT NULL,
Fare NUMERIC NOT NULL,
StartLocation NUMERIC NOT NULL,
EndLocation NUMERIC NOT NULL,
VehicleID INT NOT NULL,
PaymentID INT NOT NULL,
LocationID INT NOT NULL,
UserID INT NOT NULL,
PRIMARY KEY (RideID),
FOREIGN KEY (VehicleID) REFERENCES VEHICLE (VehicleID),
FOREIGN KEY (PaymentID) REFERENCES PAYMENT (PaymentID),
FOREIGN KEY (LocationID) REFERENCES LOCATION (LocationID),
FOREIGN KEY (UserID) REFERENCES [User](UserID)
);
